# Generated by Django 5.2 on 2025-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_image", models.ImageField(upload_to="homepage/")),
                ("main_description", models.TextField()),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
    ]
