# Generated by Django 5.2 on 2026-02-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homePage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relative_url",
                    models.CharField(max_length=200, verbose_name="آدرس url"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="speech/default.png",
                        upload_to="speech/",
                        verbose_name="تصویر بنر",
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_items",
                        to="homePage.homepage",
                    ),
                ),
            ],
        ),
    ]
