# Generated by Django 5.2 on 2026-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homePage", "0002_slideitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideitem",
            name="relative_url",
            field=models.CharField(max_length=200, null=True, verbose_name="آدرس url"),
        ),
    ]
