# Generated by Django 5.2 on 2026-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homePage", "0003_alter_slideitem_relative_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideitem",
            name="relative_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="آدرس url"
            ),
        ),
    ]
