# Generated by Django 5.2 on 2025-07-24 15:06

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="speech title"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="speech/default.jpg", upload_to="speech/"
                    ),
                ),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "title",
                "verbose_name_plural": "title",
            },
        ),
    ]
