# Generated by Django 5.2 on 2025-10-02 07:17

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(
                        help_text="از طریق این لینک کاربران می\u200cتوانند تمامی سخنرانی های مربوط به این تگ را ببیند",
                        unique=True,
                        verbose_name="لینک دسترسی به تگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="نام دسته بندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="از طریق این لینک کاربران می\u200cتوانند تمامی سخنرانی های مربوط به این دسته\u200cبندی را ببیند",
                        unique=True,
                        verbose_name="لینک دسترسی به دسته بندی",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="speech.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="عنوان سخنرانی"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="speech/default.jpg",
                        upload_to="speech/",
                        verbose_name="تصویر بنر",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp3", "wav", "ogg", "oga", "m4a", "aac", "flac"]
                            )
                        ],
                        verbose_name="فایل صوتی",
                    ),
                ),
                (
                    "audio_link",
                    models.CharField(
                        blank=True,
                        help_text="لینک مستقیم فایل سخنرانی (اگر سخنرانی را در جای دیگری آپلود کرده\u200cاید)",
                        max_length=200,
                        null=True,
                        verbose_name="لینک سخنرانی",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="لینک منحصر به فرد برای دسترسی به این سخنرانی",
                        unique=True,
                        verbose_name="لینک دسترسی",
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد افراد بازدید کننده"
                    ),
                ),
                (
                    "publish_time",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ انتشار"),
                ),
                (
                    "first_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="معرفی اولیه"
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(
                        blank=True, null=True, verbose_name="زیرنویس صوت سخنرانی"
                    ),
                ),
                (
                    "complete_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="توضیح کامل سخنرانی"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        to="speech.category", verbose_name="دسته بندی"
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, to="speech.tag", verbose_name="تگ\u200cها"
                    ),
                ),
            ],
            options={
                "verbose_name": "سخنرانی",
                "verbose_name_plural": "سخنرانی\u200cها",
            },
        ),
    ]
