# Generated by Django 5.2 on 2025-10-02 07:26

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speech",
            name="publish_time",
            field=django_jalali.db.models.jDateField(
                default=jdatetime.date.today, verbose_name="تاریخ انتشار"
            ),
        ),
    ]
