# Generated by Django 5.2 on 2025-11-12 17:17

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0002_alter_speech_publish_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "تگ", "verbose_name_plural": "تگ\u200cها"},
        ),
        migrations.AddField(
            model_name="speech",
            name="event_date_time",
            field=django_jalali.db.models.jDateField(
                default=jdatetime.date.today,
                help_text="تاریخی که مراسم و سخنرانی در اصل در آن تاریخ برگزار شده بود",
                verbose_name="تاریخ مراسم",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="speech.category",
                verbose_name="والد",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="publish_time",
            field=django_jalali.db.models.jDateField(
                default=jdatetime.date.today,
                help_text="تاریخی که میخواهید این پست به کاربران نمایش داده شود.",
                verbose_name="تاریخ مجاز نمایش",
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
    ]
