# Generated by Django 5.2 on 2025-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0003_alter_tag_options_speech_event_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speech",
            name="complete_description",
        ),
        migrations.RemoveField(
            model_name="speech",
            name="first_description",
        ),
        migrations.AddField(
            model_name="speech",
            name="sumary",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="خلاصه سخنرانی"
            ),
        ),
    ]
