# Generated by Django 5.2 on 2025-12-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0004_remove_speech_complete_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان گزینه")),
                (
                    "image",
                    models.ImageField(
                        upload_to="speech/options/", verbose_name="تصویر گزینه"
                    ),
                ),
            ],
            options={
                "verbose_name": "گزینه سخنرانی",
                "verbose_name_plural": "گزینه\u200cهای سخنرانی",
            },
        ),
        migrations.AddField(
            model_name="speech",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="مکان سخنرانی"
            ),
        ),
        migrations.AddField(
            model_name="speech",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="speeches",
                to="speech.culturalgroup",
                verbose_name="گروه فرهنگی",
            ),
        ),
    ]
