# Generated by Django 5.2 on 2025-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0005_culturalgroup_speech_location_speech_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="culturalgroup",
            options={
                "verbose_name": "گروه فرهنگی",
                "verbose_name_plural": "گروه\u200cهای فرهنگی",
            },
        ),
        migrations.AddField(
            model_name="culturalgroup",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="از طریق این لینک کاربران می\u200cتوانند تمامی سخنرانی های مربوط به این گروه فرهنگی را ببیند",
                unique=True,
                verbose_name="لینک دسترسی",
            ),
        ),
        migrations.AlterField(
            model_name="culturalgroup",
            name="image",
            field=models.ImageField(upload_to="speech/cultural/", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="culturalgroup",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
