# Generated by Django 5.2 on 2025-12-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0006_alter_culturalgroup_options_culturalgroup_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culturalgroup",
            name="slug",
            field=models.SlugField(
                help_text="از طریق این لینک کاربران می\u200cتوانند تمامی سخنرانی های مربوط به این گروه فرهنگی را ببیند",
                unique=True,
                verbose_name="لینک دسترسی",
            ),
        ),
    ]
