# Generated by Django 5.2 on 2025-12-18 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0007_alter_culturalgroup_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speech",
            name="option",
        ),
        migrations.AddField(
            model_name="speech",
            name="cultural",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cultural",
                to="speech.culturalgroup",
                verbose_name="گروه فرهنگی",
            ),
        ),
    ]
