# Generated by Django 5.2 on 2026-01-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0010_favorite_is_liked_favorite_note_speechcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speech",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, to="speech.category", verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="cultural",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cultural",
                to="speech.culturalgroup",
                verbose_name="گروه فرهنگی",
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="image",
            field=models.ImageField(
                default="speech/default.png",
                upload_to="speech/",
                verbose_name="تصویر بنر",
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="مکان سخنرانی"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="sumary",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="خلاصه سخنرانی"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="speech.tag", verbose_name="تگ\u200cها"
            ),
        ),
    ]
