# Generated by Django 5.2 on 2026-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speech", "0011_alter_speech_category_alter_speech_cultural_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speech",
            name="category",
            field=models.ManyToManyField(
                blank=True, to="speech.category", verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="speech.tag", verbose_name="تگ\u200cها"
            ),
        ),
    ]
